# Copyright (c) 2026 AIperture-Labs <xavier.beheydt@gmail.com>
# Doc: https://cmake.org/cmake/help/v4.1/index.html


set(AETHER_ENGINE_PROJECT_DIR "${CMAKE_CURRENT_SOURCE_DIR}")

set(AETHER_ENGINE_ASSETS_DIR "${AETHER_ENGINE_PROJECT_DIR}/assets")
set(AETHER_ENGINE_CACHE_DIR "${AETHER_ENGINE_PROJECT_DIR}/.cache")
set(AETHER_ENGINE_CONFIGS_DIR "${AETHER_ENGINE_PROJECT_DIR}/configs")
set(AETHER_ENGINE_DOCS_DIR "${AETHER_ENGINE_PROJECT_DIR}/docs")
set(AETHER_ENGINE_EXTERN_DIR "${AETHER_ENGINE_PROJECT_DIR}/extern")
set(AETHER_ENGINE_RUNTIMES_DIR "${AETHER_ENGINE_PROJECT_DIR}/runtimes")
set(AETHER_ENGINE_SHADERS_DIR "${AETHER_ENGINE_ASSETS_DIR}/shaders")
set(AETHER_ENGINE_SOURCE_DIR "${AETHER_ENGINE_PROJECT_DIR}/sources")
set(AETHER_ENGINE_TESTS_DIR "${AETHER_ENGINE_PROJECT_DIR}/tests")
set(AETHER_ENGINE_TEXTURES_DIR "${AETHER_ENGINE_ASSETS_DIR}/textures")